name: Docker Images CI

on:
  schedule:
  - cron: "0 2 * * 1-5"
  workflow_dispatch:


jobs:
  build-r1Core2:
    runs-on: ubuntu-latest
    steps:
    - name: Change docker to experimental mode
      run: |
       echo '{"experimental": true}' | sudo tee -a /etc/docker/daemon.json
    - run: cat /etc/docker/daemon.json
    - name: Restart docker daemon
      run: sudo systemctl restart docker
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --squash --tag konkarapas/r1images:r1Core2 ../../docker_stuff/docker_core2/Dockerfile
