name: Docker Images CI

on:
  schedule:
  - cron: "0 2 * * 1-5"
  workflow_dispatch:


jobs:
  build-r1Core2:
    runs-on: ubuntu-latest
    steps:
    - name: Remove old docker conf
      run: sudo rm -rf /etc/docker/daemon.json
    - name: Change docker to experimental mode
      run: |
       echo '{"experimental": true}' | sudo tee -a /etc/docker/daemon.json
    - name: Restart docker daemon
      run: sudo systemctl restart docker
    - uses: actions/checkout@v3.0.
      with:
        path: 'docker_stuff/docker_core2'
    - name: Build the Docker image
      run: |
       echo $PWD
       cd docker_stuff/docker_core2/
       docker build --squash --tag konkarapas/r1images:r1Core2 docker_stuff/docker_core2/Dockerfile
