name: Docker Images CI

on:
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  build-r1Core2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ros2_support
    - name: Build the Docker image
      run: docker build --squash --tag konkarapas/r1images:r1Core2 ../../docker_stuff/docker_core2/Dockerfile
